package online.weiyin;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import springfox.documentation.swagger2.annotations.EnableSwagger2;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@EnableSwagger2
public class SchoollinkDevApplication {

    public static void main(String[] args) {
        SpringApplication.run(SchoollinkDevApplication.class, args);
    }

}
