spring:
  datasource:
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/schoollink?&useSSL=false&serverTimezone=UTC
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  flyway:
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
    clean-disabled: false
sa-token:
  token-name: schoollink
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: true
logging:
  config: classpath:logback/logback-dev.xml
springfox:
  documentation:
    swagger-ui:
      enabled: true
